spring.application.name=gro_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/gro_backend
spring.datasource.username=postgres
spring.datasource.password=sakshi123

spring.jpa.hibernate.ddl-auto=update


